# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [4]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    Генерує матрицю розміром dim x dim з цілими числами від 0 до 10.
    """
    matrix = np.random.randint(10, size=(dim, dim))
    return matrix
def permutations(k):
    """
    Генерує всі можливі перестановки чисел від 1 до k.
    """
    return list(itertools.permutations(range(1, k + 1)))
def multiplication(matrix, permutation):
    """
    Обчислює добуток елементів матриці, використовуючи дану перестановку.
    """
    result = 1
    for i in range(len(permutation)):
        result *= matrix[i][permutation[i] - 1]
    return result
def determinant(matrix):
    """
    Обчислює визначник матриці за допомогою методу перестановок.
    """
    n = len(matrix)
    permutations1 = permutations(n)
    det = 0
    for perm in permutations1:
        result = multiplication(matrix, perm)
        signofdet = 1
        for i in range(n):
            for m in range(i + 1, n):
                if perm[i] > perm[m]:
                    signofdet *= -1
        det += signofdet * result
    return det
dim = int(input("Введіть розмірність матриці: "))
if dim <= 0:
    print("Введіть додатне число, відмінне від нуля.")
else:
    matrix = random_matrix(dim)
    print("Ваша випадкова матриця:")
    print(matrix)
    det = determinant(matrix)
    print("Визначник матриці, обчислений методом перестановок:", det)
    check = np.linalg.det(matrix)
    print("Перевірка визначника:", check)

[[4 6 5]
 [7 1 7]
 [0 9 9]]
